---
title: "空间转录组测序质量控制报告"
author: "上海交通大学医学院上海市免疫学研究所测序平台"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    number_sections: true
    center: true
    theme: bootstrap
    highlight: zenburn
vignette: >
  %\VignetteIndexEntry{空间转录组测序质量控制报告}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 120
---

```{=html}
<style>
.vscroll-plot {
    width: 1000px;
    height: 400px;
    overflow-y: scroll;
}
.hscroll-plot {
    width: 500px;
    height: 400px;
    overflow-x: scroll;
}
</style>
```
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy = FALSE,
  cache = FALSE,
  dev = "png"
)

##### packages and settings #####
showtext::showtext_auto(enable = T)
tryCatch(
  sysfonts::font_add('Songti', 'Songti.ttc'),
  error = function(e) {
    stop("Please install 'Songti.ttc' into path ~/.fonts/ and then run the command 'fc-cache -vf'!\nPlatform exits")
  }
)

`%>%` <- dplyr::`%>%`
```

------------------------------------------------------------------------------------------------------------------------

# 背景介绍

-   空间转录组（Spatial
    Transcriptomics）可以整合基因表达与组织切片免疫化学染色图像，从而将组织内不同细胞的基因表达信息定位于其原始空间位置，进而直接观测组织中不同功能区之间基因表达的差异。此技术综合了常规的原位技术和组学技术的优势。
-   2016年Joakim Lundeberg的Spatial Transcriptomics技术在Science上发表；2017年景乃禾的GEO-seq技术在Nature
    Protocols上发表。目前已发表的关于空间转录组技术有主要有Spatial Transcriptomics、
    Slide-seq、LCM-seq、seqFISH、MERFISH、Liver single cell zonation、Geo-seq和Tomo-seq。
    涉及物种有人、小鼠、果蝇、秀丽隐杆线虫、斑马鱼、拟南芥、杨树和云杉等。

------------------------------------------------------------------------------------------------------------------------

# 仪器设备

|    **仪器**     | **型号** | **供应商** |
|:---------------:|:--------:|:----------:|
|      PCR仪      |   xxx    |    xxx     |
| 2100 生物分析仪 |   xxx    |    xxx     |
| 荧光倒置显微镜  |   xxx    |    xxx     |
|   冷冻切片机    |   xxx    |    xxx     |

------------------------------------------------------------------------------------------------------------------------

# 试剂及耗材

| **名称** | **编号** | **供应商** |
|:--------:|:--------:|:----------:|
|   xxx    |   xxx    |    xxx     |
|   xxx    |   xxx    |    xxx     |
|   xxx    |   xxx    |    xxx     |
|   xxx    |   xxx    |    xxx     |

------------------------------------------------------------------------------------------------------------------------

# 组织样本制备

## 样本包埋

1.  将OCT及镊子置于冰上≥30分钟。
2.  用异戊烷填充三分之二的金属烧杯（以完全浸没组织），后将其放入液氮中（与异戊烷相同的液位）以充分接触。孵育15分钟。
3.  使用实验室用纸，从吸干组织表面的液体。
4.  在包埋盒上标记组织样本的情况及方向，使用OCT包埋包埋盒底部。
5.  使用预冷的镊子，将组织放在OCT上，继续倒入OCT以完全覆盖样本。
6.  用镊子将包埋盒放置到异戊烷中，浸没至包埋盒顶部，直到OCT冻结。
7.  立即将含有组织和OCT的包埋盒放在干冰粉上。
8.  将OCT包埋组织块保存在--80ºC的密封容器中，以便长期保存，或立即进行冷冻切片。

## 冷冻切片 {#冷冻切片}

1.  将OCT块修至适宜大小。
2.  冷冻切片机温度设置：冷冻切片机腔体设定温度为-20℃，冻头设定温度为-10℃。
3.  将OCT包埋组织块放在样品台上，使切割面背对样品台。将样品台和组织块放在冷冻切片机内的不锈钢冷冻台上。使OCT和组织块冻结并粘附到样品台上。
4.  切取2片至普通玻片上，后续HE染色。
5.  切取10-15片，厚度为10 µm，放置2ml冻存中，-80℃保存或立即RNA提取。

## RNA质量评估

-   使用Qiagen RNeasy Mini Kit进行RNA提取。
-   使用Agilent 2100进行质检。

**！！！质检结果！！！**

## 样本固定、H&E染色及成像 {#lll}

1.  取40ml甲醇于50毫升离心管中。
2.  将PCR仪适配器放在设定为37°C的PCR仪上，平衡5分钟。不需要加热PCR仪盖。
3.  将载玻片放在PCR仪适配器上，有切片的一面朝上，在37°C下孵育1分钟。勿关闭PCR仪盖。在染色步骤中一直将PCR仪维持在37°C。
4.  擦去载玻片背面多余液体，不要接触到组织部分。
5.  将载玻片完全浸入预冷的甲醇中，扣紧管盖，-20°C孵育30分钟。
6.  在50 ml离心管中放入50 ml Milli-Q水，在烧杯1、2、3中各加入800ml的Milli-Q水，每个烧杯中超纯水的体积可用于两个芯片。
7.  从甲醇中取出载玻片，并从载玻片背面擦去多余的液体，不可接触到组织切片。之后将其放在平坦，干净的工作台上，可能会残留一些液滴。
8.  滴加500μl异丙醇以均匀覆盖所有组织切片，室温下孵育1分钟。
9.  将玻片倾斜，使载玻片底边缘与纸巾接触，吸收多余试剂，风干载玻片。
10. 加入1 ml苏木精均匀覆盖玻片上的所有组织切片,室温下孵育7分钟。
11. 将玻片倾斜,使载玻片底边缘与纸巾接触，吸收多余试剂。
12. 将载玻片浸入50ml离心管的水中5次；浸入烧杯1的水中15次；浸入烧杯2的水中15次。
13. 擦去载玻片背面多余的液体。
14. 加入1 ml Bluing Buffer均匀覆盖所有组织切片。在室温下孵育2分钟。
15. 将玻片倾斜，使载玻片底边缘与纸巾接触，吸收多余试剂。
16. 将载玻片浸入烧杯2的水中5次。
17. 擦去载玻片背面多余的液体。
18. 加入1 ml伊红混合物以均匀覆盖所有组织切片，室温下孵育1分钟。
19. 将玻片倾斜，使载玻片底边缘与纸巾接触，吸收多余试剂。将载玻片浸入烧杯3的水中15次。将其放在工作台上，风干直至组织不透明。
20. 保持PCR仪的盖打开，在37°C下孵育载玻片5分钟后，进行成像实验。

**！！！样本明场图像镜检照片！！！**

------------------------------------------------------------------------------------------------------------------------

# 组织优化实验

## 冷冻切片

-   切取7片组织切片放置在Visium 空间基因表达中组织优化芯片的捕获区域（B1-D2）内，A1用于阳性RNA对照。

## 样本固定、H&E染色及成像

-   具体实验步骤[同上](#lll)。

## 样本透化及荧光cDNA的合成

-   具体实验流程参照附件：CG000238\_ Visium Spatial Gene Expression Reagent Kits - Tissue Optimization

**！！！样本明场图像及荧光图像镜检照片！！！**

**！！！样本透化时间选择结果！！！**

------------------------------------------------------------------------------------------------------------------------

# 基因表达实验

## 冷冻切片

-   具体实验流程[同上](#冷冻切片)。

## 样本固定、H&E染色及成像

-   具体实验步骤[同上](#lll)。

**！！！样本镜检照片！！！**

## 样本透化及反转录、二链合成、变性和cDNA扩增及质检

-   具体实验流程参照附件： CG000239_Visium Spatial Gene Expression User Guide RevC

**！！！cDNA质检结果！！！**

**！！！Agilent 2100 Bioanalyzer检测峰图！！！**

## 测序文库构建

1.  cDNA扩增完成后，酶切片段化并磁珠筛选最适片段，通过末端修复、加A、接头连接Read2测序引物，再以PCR方式构建含有P5和P7接头的cDNA文库。
2.  文库用磁珠进行纯化。
3.  文库使用 Qubit检测浓度，Agilent 2100检测片段大小。

**！！！文库质检结果！！！**

**！！！Agilent 2100 Bioanalyzer检测峰图！！！**

## 上机测序

-   按照Illumina User Guide完成 Cluster生成和第一向测序引物杂交，将携有cluster的flow
    cell上机。选用paired-end程序，进行双端测序。
-   测序过程由 Illumina提供的data collection software进行控制，并进行实时数据分析。
